import { SiteContent } from './types';

export const initialSiteContent: SiteContent = {
  settings: {
    siteTitle: 'PROJECT NEON — Autonomous Interactive Platform',
    siteDescription: 'Crafting visionary digital experiences, spatial neon interfaces, and real-time content systems.',
    themeMode: 'dark',
    accentColor: '#06b6d4',
  },
  navigation: [
    { id: 'nav-1', label: 'Idea', url: '#about', order: 1 },
    { id: 'nav-2', label: 'System', url: '#features', order: 2 },
    { id: 'nav-3', label: 'Metrics', url: '#stats', order: 3 },
    { id: 'nav-4', label: 'Work', url: '#gallery', order: 4 },
    { id: 'nav-5', label: 'Journey', url: '#timeline', order: 5 },
    { id: 'nav-6', label: 'Signal', url: '#testimonials', order: 6 },
  ],
  hero: {
    badgeText: 'PROJECT NEON 3.0 • NEXT-GEN INTERACTIVE OS',
    headline: 'ENGINEER THE',
    highlightText: 'FUTURE NOW.',
    subtitle: 'PROJECT NEON combines tactile glass interfaces with autonomous computational intelligence to power high-impact digital products.',
    primaryCtaText: 'Explore Showcase',
    primaryCtaUrl: '#gallery',
    secondaryCtaText: 'Launch Admin CMS',
    secondaryCtaUrl: '/admin',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1600&auto=format&fit=crop',
    showScrollIndicator: true,
    isVisible: true,
  },
  about: {
    badge: 'THE IDEA',
    title: 'Precision engineering meets spatial neon aesthetics.',
    description: 'PROJECT NEON is built on the belief that digital products should feel physical, ultra-responsive, and visually memorable. We engineer interfaces that elevate user engagement through glassmorphic depth and sub-millisecond real-time content sync.',
    secondaryDescription: 'Designed for elite creative teams, modern SaaS enterprises, and digital visionaries worldwide.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    statValue: '99.9%',
    statLabel: 'Real-Time Sync Precision',
    isVisible: true,
  },
  features: {
    title: 'THE SYSTEM',
    subtitle: 'Full-spectrum capabilities designed for modern autonomous web platforms.',
    isVisible: true,
    items: [
      {
        id: 'feat-1',
        iconName: 'Sparkles',
        title: 'Tactile Glass Design Language',
        description: 'Refined Apple-inspired glass surfaces with electric cyan specular lighting and fluid micro-interactions.',
        badge: 'NEON CORE',
        order: 1,
        isVisible: true,
      },
      {
        id: 'feat-2',
        iconName: 'Zap',
        title: 'Real-Time Supabase Engine',
        description: 'Instant split-screen CMS editing backed by Supabase PostgreSQL with isolated draft and live publish RLS policies.',
        badge: 'SUPABASE CMS',
        order: 2,
        isVisible: true,
      },
      {
        id: 'feat-3',
        iconName: 'Cpu',
        title: 'Edge-Rendered Web Core',
        description: 'Next.js 14 App Router with instant cache revalidation and dynamic database state sync.',
        order: 3,
        isVisible: true,
      },
      {
        id: 'feat-4',
        iconName: 'ShieldCheck',
        title: 'Supabase Auth & RLS Guard',
        description: 'Database-enforced Row Level Security ensuring only verified administrators can save or publish content.',
        order: 4,
        isVisible: true,
      },
      {
        id: 'feat-5',
        iconName: 'Layers',
        title: 'Spatial Preview Infrastructure',
        description: '3D viewport tilt surfaces, responsive device frames, and spring-physics animations.',
        order: 5,
        isVisible: true,
      },
      {
        id: 'feat-6',
        iconName: 'Globe',
        title: 'High-Availability Media Vault',
        description: 'Direct integration with Supabase Storage for optimized asset uploading and global CDN delivery.',
        order: 6,
        isVisible: true,
      },
    ],
  },
  stats: {
    title: 'THE METRICS',
    subtitle: 'Empirical results engineered across global PROJECT NEON deployments.',
    isVisible: true,
    items: [
      {
        id: 'stat-1',
        number: '150+',
        label: 'Global Deployments',
        description: 'Live interactive platforms',
        order: 1,
        isVisible: true,
      },
      {
        id: 'stat-2',
        number: '$2.1B+',
        label: 'Client Capital Raised',
        description: 'By partner enterprises',
        order: 2,
        isVisible: true,
      },
      {
        id: 'stat-3',
        number: '52',
        label: 'Design Honors',
        description: 'Awwwards & FWA recognitions',
        order: 3,
        isVisible: true,
      },
      {
        id: 'stat-4',
        number: '99.99%',
        label: 'System Uptime',
        description: 'Supabase cloud SLA',
        order: 4,
        isVisible: true,
      },
    ],
  },
  gallery: {
    title: 'THE WORK',
    subtitle: 'Explore flagship platforms built with PROJECT NEON design standards.',
    categories: ['All', 'SaaS', 'Spatial UI', 'Brand System', 'Mobile OS'],
    isVisible: true,
    items: [
      {
        id: 'gal-1',
        title: 'NEON OS — Spatial Workspace',
        category: 'Spatial UI',
        description: 'Next-generation glass desktop environment featuring fluid canvas nodes and window dynamics.',
        imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
        linkUrl: '#',
        order: 1,
        isVisible: true,
      },
      {
        id: 'gal-2',
        title: 'Apex Financial Console',
        category: 'SaaS',
        description: 'Ultra-low latency institutional trading dashboard with dark-mode glass telemetry widgets.',
        imageUrl: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?q=80&w=1200&auto=format&fit=crop',
        linkUrl: '#',
        order: 2,
        isVisible: true,
      },
      {
        id: 'gal-3',
        title: 'Vanguard Brand Identity',
        category: 'Brand System',
        description: 'Generative typography system and 3D visual language for an autonomous AI research lab.',
        imageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=1200&auto=format&fit=crop',
        linkUrl: '#',
        order: 3,
        isVisible: true,
      },
      {
        id: 'gal-4',
        title: 'Quantum Mobile Experience',
        category: 'Mobile OS',
        description: 'Biometric gesture-driven mobile app architecture for decentralized asset management.',
        imageUrl: 'https://images.unsplash.com/photo-1616469829941-c7200edec809?q=80&w=1200&auto=format&fit=crop',
        linkUrl: '#',
        order: 4,
        isVisible: true,
      },
    ],
  },
  timeline: {
    title: 'THE JOURNEY',
    subtitle: 'Key milestones in the evolution of PROJECT NEON.',
    isVisible: true,
    items: [
      {
        id: 'time-1',
        year: '2026',
        title: 'PROJECT NEON + Supabase CMS',
        description: 'Integrated PostgreSQL draft/publish database system with Supabase Auth and RLS guards.',
        tag: 'MAJOR RELEASE',
        order: 1,
        isVisible: true,
      },
      {
        id: 'time-2',
        year: '2025',
        title: 'Electric Neon Glass Standard',
        description: 'Pioneered luminous cyan-violet specular highlight system for interactive spatial web UIs.',
        tag: 'DESIGN REVOLUTION',
        order: 2,
        isVisible: true,
      },
      {
        id: 'time-3',
        year: '2024',
        title: 'Global Enterprise Expansion',
        description: 'Deployed high-performance platforms across Silicon Valley, London, and Tokyo.',
        tag: 'EXPANSION',
        order: 3,
        isVisible: true,
      },
      {
        id: 'time-4',
        year: '2023',
        title: 'Founding of PROJECT NEON',
        description: 'Initiated research into autonomous UI components and real-time live preview editing.',
        tag: 'FOUNDATION',
        order: 4,
        isVisible: true,
      },
    ],
  },
  testimonials: {
    title: 'THE SIGNAL',
    subtitle: 'Feedback from technology leaders building with PROJECT NEON.',
    isVisible: true,
    items: [
      {
        id: 'test-1',
        name: 'Elena Rostova',
        role: 'Chief Design Officer',
        company: 'Vanguard Systems',
        quote: 'PROJECT NEON delivered the exact futuristic Apple-level aesthetic we needed. The Supabase publish flow gives our editorial team complete freedom.',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
        rating: 5,
        order: 1,
        isVisible: true,
      },
      {
        id: 'test-2',
        name: 'Marcus Vance',
        role: 'Founder & CEO',
        company: 'Apex Capital',
        quote: 'The electric cyan glass accents look incredible. The split-screen live CMS updates in real time without any lag.',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
        rating: 5,
        order: 2,
        isVisible: true,
      },
      {
        id: 'test-3',
        name: 'Sarah Chen',
        role: 'VP of Product',
        company: 'NEON Tech Labs',
        quote: 'Replacing mock storage with real Supabase Auth and database persistence transformed this into a true production-grade CMS platform.',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
        rating: 5,
        order: 3,
        isVisible: true,
      },
    ],
  },
  cta: {
    title: 'ENTER THE FUTURE.',
    subtitle: 'Transform your web platform with PROJECT NEON and real Supabase CMS control.',
    primaryCtaText: 'Launch Admin CMS',
    primaryCtaUrl: '/admin',
    secondaryCtaText: 'Explore Technical System',
    secondaryCtaUrl: '#features',
    backgroundGlow: 'radial-gradient(circle at 50% 50%, rgba(6, 182, 212, 0.25) 0%, rgba(0, 0, 0, 0) 70%)',
    isVisible: true,
  },
  footer: {
    brandName: 'PROJECT NEON',
    tagline: 'Autonomous digital products & Supabase content architecture.',
    contactEmail: 'hello@projectneon.design',
    contactAddress: '700 Montgomery St, San Francisco, CA',
    copyrightText: '© 2026 PROJECT NEON Inc. All rights reserved.',
    socialLinks: {
      github: 'https://github.com',
      twitter: 'https://twitter.com',
      linkedin: 'https://linkedin.com',
      instagram: 'https://instagram.com',
    },
    isVisible: true,
  },
};
