import { SiteContent } from './types';

export const initialSiteContent: SiteContent = {
  settings: {
    siteTitle: 'PROJECT NEON — Managed Website-as-a-Service Infrastructure Platform',
    siteDescription: 'Lease, manage, and continuously evolve your company’s digital advertising platform with remote Supabase CMS control.',
    themeMode: 'dark',
    accentColor: '#38bdf8',
  },
  navigation: [
    { id: 'nav-1', label: 'Presence', url: '#about', order: 1 },
    { id: 'nav-2', label: 'WaaS System', url: '#features', order: 2 },
    { id: 'nav-3', label: 'Solutions', url: '#solutions', order: 3 },
    { id: 'nav-4', label: 'Command Center', url: '#command-center', order: 4 },
    { id: 'nav-5', label: 'Trust & SLA', url: '#trust', order: 5 },
    { id: 'nav-6', label: 'Impact', url: '#stats', order: 6 },
  ],
  hero: {
    badgeText: 'PROJECT NEON • MANAGED WEBSITE-AS-A-SERVICE (WAAS)',
    headline: 'YOUR DIGITAL PLATFORM,',
    highlightText: 'ALWAYS LIVE.',
    subtitle: 'PROJECT NEON provides modern companies with leased, high-performance digital advertising infrastructure — featuring real-time remote editing, managed cloud infrastructure, and liquid glass design.',
    primaryCtaText: 'Deploy Your Digital Platform',
    primaryCtaUrl: '#solutions',
    secondaryCtaText: 'Explore Enterprise Partnership',
    secondaryCtaUrl: '#trust',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1600&auto=format&fit=crop',
    showScrollIndicator: true,
    isVisible: true,
  },
  about: {
    badge: 'ENTERPRISE DIGITAL PRESENCE',
    title: 'High-performance digital advertising platforms without the cost or delay of traditional web builds.',
    description: 'Instead of spending months and heavy capital on static website development, PROJECT NEON provides a complete Website-as-a-Service model. We deliver custom-crafted liquid glass platforms with continuous hosting, security maintenance, and instant remote content control.',
    secondaryDescription: 'Engineered for high-growth startups, enterprise marketing teams, and global brands that require a digital presence that evolves continuously.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    statValue: '10X',
    statLabel: 'Faster Campaign Launch',
    isVisible: true,
  },
  features: {
    title: 'THE WAAS INFRASTRUCTURE SYSTEM',
    subtitle: 'Full-spectrum managed platform built for high-impact enterprise advertising.',
    isVisible: true,
    items: [
      {
        id: 'feat-1',
        iconName: 'Zap',
        title: 'Live Remote Content Control',
        description: 'Update your campaigns, announcements, and brand media remotely without touching code or waiting on developers.',
        badge: 'REMOTE CMS',
        order: 1,
        isVisible: true,
      },
      {
        id: 'feat-2',
        iconName: 'Globe',
        title: 'Managed Cloud Infrastructure',
        description: 'Zero server maintenance. High-availability hosting, Supabase PostgreSQL database, and global CDN delivery included.',
        badge: 'MANAGED HOSTING',
        order: 2,
        isVisible: true,
      },
      {
        id: 'feat-3',
        iconName: 'Sparkles',
        title: 'Liquid Crystal Design System',
        description: 'Apple VisionOS inspired glassmorphic interface engineered to captivate customers and elevate brand authority.',
        badge: 'PREMIUM DESIGN',
        order: 3,
        isVisible: true,
      },
      {
        id: 'feat-4',
        iconName: 'Cpu',
        title: 'Real-Time Campaign Publishing',
        description: 'Launch seasonal promotions and product announcements instantly with instant cache revalidation across global edge nodes.',
        order: 4,
        isVisible: true,
      },
      {
        id: 'feat-5',
        iconName: 'ShieldCheck',
        title: 'Supabase Enterprise Security',
        description: 'Database-enforced Row Level Security (RLS) ensuring only authorized marketing admins can save or publish content.',
        order: 5,
        isVisible: true,
      },
      {
        id: 'feat-6',
        iconName: 'Layers',
        title: 'Continuous Digital Evolution',
        description: 'Platform design refinements, security patches, and feature upgrades maintained continuously as part of your lease.',
        order: 6,
        isVisible: true,
      },
    ],
  },
  stats: {
    title: 'ENTERPRISE IMPACT',
    subtitle: 'Empirical performance results delivered across leased digital platforms.',
    isVisible: true,
    items: [
      {
        id: 'stat-1',
        number: '150+',
        label: 'Leased Platforms',
        description: 'Active enterprise clients',
        order: 1,
        isVisible: true,
      },
      {
        id: 'stat-2',
        number: '< 340ms',
        label: 'Remote Sync Speed',
        description: 'Instant database publishing',
        order: 2,
        isVisible: true,
      },
      {
        id: 'stat-3',
        number: '99.99%',
        label: 'Cloud SLA Uptime',
        description: 'Managed Supabase infrastructure',
        order: 3,
        isVisible: true,
      },
      {
        id: 'stat-4',
        number: '10X',
        label: 'Faster Campaign Launch',
        description: 'Zero developer dependency',
        order: 4,
        isVisible: true,
      },
    ],
  },
  gallery: {
    title: 'MANAGED PLATFORMS',
    subtitle: 'Explore flagship digital advertising platforms leased and operated by client brands.',
    categories: ['All', 'Enterprise SaaS', 'Spatial Retail', 'Brand Systems', 'Financial Consoles'],
    isVisible: true,
    items: [
      {
        id: 'gal-1',
        title: 'NEON OS — Spatial Workspace Platform',
        category: 'Enterprise SaaS',
        description: 'Leased digital advertising platform featuring fluid glass node views and live marketing telemetry.',
        imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
        linkUrl: '#',
        order: 1,
        isVisible: true,
      },
      {
        id: 'gal-2',
        title: 'Apex Financial Console Platform',
        category: 'Financial Consoles',
        description: 'Institutional trading platform presentation managed remotely with live data widgets.',
        imageUrl: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?q=80&w=1200&auto=format&fit=crop',
        linkUrl: '#',
        order: 2,
        isVisible: true,
      },
      {
        id: 'gal-3',
        title: 'Vanguard Brand Identity Platform',
        category: 'Brand Systems',
        description: 'Continuously managed digital platform for an autonomous AI research and consulting firm.',
        imageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=1200&auto=format&fit=crop',
        linkUrl: '#',
        order: 3,
        isVisible: true,
      },
      {
        id: 'gal-4',
        title: 'Quantum Mobile Brand Platform',
        category: 'Spatial Retail',
        description: 'Managed mobile-first advertising presence for decentralized asset management applications.',
        imageUrl: 'https://images.unsplash.com/photo-1616469829941-c7200edec809?q=80&w=1200&auto=format&fit=crop',
        linkUrl: '#',
        order: 4,
        isVisible: true,
      },
    ],
  },
  timeline: {
    title: 'THE WAAS PARTNERSHIP MODEL',
    subtitle: 'How PROJECT NEON replaces traditional web builds with continuous digital infrastructure management.',
    isVisible: true,
    items: [
      {
        id: 'time-1',
        year: 'Step 01',
        title: 'Custom Platform Provisioning',
        description: 'We craft and deploy your company’s liquid glass digital advertising platform on high-availability edge nodes.',
        tag: 'PROVISION',
        order: 1,
        isVisible: true,
      },
      {
        id: 'time-2',
        year: 'Step 02',
        title: 'Remote CMS Portal Handover',
        description: 'Your marketing team receives secure Supabase Auth credentials for real-time remote editing.',
        tag: 'ENABLE',
        order: 2,
        isVisible: true,
      },
      {
        id: 'time-3',
        year: 'Step 03',
        title: 'Instant Campaign Launch',
        description: 'Publish announcements, banners, and product showcases live in seconds without touching code.',
        tag: 'EXECUTE',
        order: 3,
        isVisible: true,
      },
      {
        id: 'time-4',
        year: 'Step 04',
        title: 'Continuous Evolution & SLA',
        description: 'Hosting, security patches, performance updates, and design upgrades maintained perpetually under your lease.',
        tag: 'EVOLVE',
        order: 4,
        isVisible: true,
      },
    ],
  },
  testimonials: {
    title: 'ENTERPRISE TESTIMONIALS',
    subtitle: 'Verified business results from marketing directors, CMOs, and enterprise leaders.',
    isVisible: true,
    items: [
      {
        id: 'test-1',
        name: 'Elena Rostova',
        role: 'Chief Marketing Officer',
        company: 'Vanguard Systems',
        quote: 'PROJECT NEON replaced our $80k annual website maintenance budget with a seamless WaaS platform lease. Our marketing team updates campaign pages in seconds.',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
        rating: 5,
        order: 1,
        isVisible: true,
      },
      {
        id: 'test-2',
        name: 'Marcus Vance',
        role: 'VP of Growth',
        company: 'Apex Capital',
        quote: 'Having a managed digital advertising platform with instant remote editing changed our campaign velocity completely. We launch product pages 10x faster.',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
        rating: 5,
        order: 2,
        isVisible: true,
      },
      {
        id: 'test-3',
        name: 'Sarah Chen',
        role: 'Brand Director',
        company: 'NEON Tech Labs',
        quote: 'The liquid glass design wows our institutional clients, while the Supabase backend gives our marketing team complete remote autonomy.',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
        rating: 5,
        order: 3,
        isVisible: true,
      },
    ],
  },
  cta: {
    title: 'DEPLOY YOUR DIGITAL INFRASTRUCTURE.',
    subtitle: 'Lease a high-performance digital advertising platform with real-time remote Supabase CMS control today.',
    primaryCtaText: 'Deploy Your Digital Platform',
    primaryCtaUrl: '/admin',
    secondaryCtaText: 'Schedule Platform Consultation',
    secondaryCtaUrl: '#trust',
    backgroundGlow: 'radial-gradient(circle at 50% 50%, rgba(56, 189, 248, 0.25) 0%, rgba(0, 0, 0, 0) 70%)',
    isVisible: true,
  },
  footer: {
    brandName: 'PROJECT NEON',
    tagline: 'Managed Website-as-a-Service (WaaS) Platform Infrastructure & Remote Content Control.',
    contactEmail: 'solutions@projectneon.design',
    contactAddress: '700 Montgomery St, San Francisco, CA',
    copyrightText: '© 2026 PROJECT NEON Inc. All rights reserved.',
    socialLinks: {
      github: 'https://github.com',
      twitter: 'https://twitter.com',
      linkedin: 'https://linkedin.com',
      instagram: 'https://instagram.com',
    },
    isVisible: true,
  },
};
